using System.Collections.Generic;

namespace LinearPartitioning
{
	public static class SampleData
	{
		public static readonly IReadOnlyList<RecordInfo> Records = new RecordInfo[]
		{
			new RecordInfo { Name = "Introductions", Duration = "04:54" },
			new RecordInfo { Name = "Nationalities", Duration = "05:34" },
			new RecordInfo { Name = "Numbers", Duration = "06:46" },
			new RecordInfo { Name = "Jobs", Duration = "07:01" },
			new RecordInfo { Name = "The Alphabet", Duration = "06:24" },
			new RecordInfo { Name = "Bar Food", Duration = "06:14" },
			new RecordInfo { Name = "Drinks", Duration = "05:48" },
			new RecordInfo { Name = "In A Bar", Duration = "03:02" },
			new RecordInfo { Name = "Restaurant Food", Duration = "03:42" },
			new RecordInfo { Name = "In A Restaurant", Duration = "03:32" },
			new RecordInfo { Name = "Directions", Duration = "04:38" },
			new RecordInfo { Name = "Shops & Other Buildings", Duration = "06:02" },
			new RecordInfo { Name = "Locations", Duration = "04:50" },
			new RecordInfo { Name = "North, East, South & West", Duration = "02:04" },
			new RecordInfo { Name = "Distances & Numbers 100 - 1000", Duration = "03:04" },
			new RecordInfo { Name = "The Family", Duration = "07:00" },
			new RecordInfo { Name = "Verb To Be - Verbo Ser", Duration = "05:23" },
			new RecordInfo { Name = "Verbo Ser & The Family", Duration = "03:23" },
			new RecordInfo { Name = "Verb To Have - Verbo Tener", Duration = "05:39" },
			new RecordInfo { Name = "Verbo Tener & The Family", Duration = "04:18" },
			new RecordInfo { Name = "Physical Descriptions", Duration = "06:33" },
			new RecordInfo { Name = "Physical Decriptions With Verbos Ser & Tener", Duration = "06:30" },
			new RecordInfo { Name = "Describing Personality", Duration = "05:09" },
			new RecordInfo { Name = "Verb To Be - Verbo Estar", Duration = "04:16" },
			new RecordInfo { Name = "Feelings", Duration = "06:34" },
			new RecordInfo { Name = "Spanish Verbs", Duration = "02:05" },
			new RecordInfo { Name = "Present Tense - Regular Verbs (Part 1)", Duration = "06:46" },
			new RecordInfo { Name = "Present Tense - Regular Verbs (Part 2)", Duration = "07:39" },
			new RecordInfo { Name = "The Time (Part 1)", Duration = "05:56" },
			new RecordInfo { Name = "The Time (Part 2)", Duration = "06:21" },
			new RecordInfo { Name = "Shopping For Food (Part 1)", Duration = "03:51" },
			new RecordInfo { Name = "Shopping For Food (Part 2)", Duration = "08:40" },
			new RecordInfo { Name = "Clothes", Duration = "03:17" },
			new RecordInfo { Name = "The Colours", Duration = "04:50" },
			new RecordInfo { Name = "Shopping For Clothes", Duration = "06:56" },
			new RecordInfo { Name = "Verb To Go - Verbo Ir", Duration = "04:38" },
			new RecordInfo { Name = "Transport (Part 1)", Duration = "02:39" },
			new RecordInfo { Name = "Transport (Part 2)", Duration = "05:32" },
			new RecordInfo { Name = "Comparatives", Duration = "06:12" },
			new RecordInfo { Name = "Irregular Comparatives", Duration = "06:33" },
			new RecordInfo { Name = "Need & Interest (Part 1)", Duration = "04:17" },
			new RecordInfo { Name = "Need & Interest (Part 2)", Duration = "04:23" },
			new RecordInfo { Name = "Need & Interest (Part 3)", Duration = "05:09" },
			new RecordInfo { Name = "Travelling (Part 1)", Duration = "03:29" },
			new RecordInfo { Name = "Travelling (Part 2)", Duration = "04:29" },
			new RecordInfo { Name = "Reflexive Verbs - Verbos Reflexivos (Part 1)", Duration = "02:31" },
			new RecordInfo { Name = "Reflexive Verbs - Verbos Reflexivos (Part 2)", Duration = "04:44" },
			new RecordInfo { Name = "Reflexive Verbs - Verbos Reflexivos (Part 3)", Duration = "05:43" },
			new RecordInfo { Name = "Days Of The Week", Duration = "02:24" },
			new RecordInfo { Name = "Months Of The Year", Duration = "03:27" },
			new RecordInfo { Name = "Irregular Verbs In Present Tense (Part 1)", Duration = "04:01" },
			new RecordInfo { Name = "Irregular Verbs In Present Tense (Part 2)", Duration = "04:14" },
			new RecordInfo { Name = "Irregular Verbs In Present Tense (Part 3)", Duration = "03:39" },
			new RecordInfo { Name = "Irregular Verbs In Present Tense (Part 4)", Duration = "04:17" },
			new RecordInfo { Name = "Irregular Verbs In Present Tense (Part 5)", Duration = "03:05" },
			new RecordInfo { Name = "Adverbs Of Frequency", Duration = "03:19" },
			new RecordInfo { Name = "Frequency Expressions", Duration = "04:11" },
			new RecordInfo { Name = "Hobbies & Leisure", Duration = "02:28" }
		};
	}
}
